### ISSUE TITLE
Upload to Hackage?

### ISSUE THREAD

**Issue by FranklinChen** [ocharles/pipes-tar#3]
I was looking for a stream tar library and found this repo but it's not up on Hackage.

**Comment by ocharles** [comment]
Indeed, I was always planning to finish it off... to the point where I now can't remember what really needs finishing :) Have you had a play with it? If so, does it do what you want?

**Comment by YellowOnion** [comment]
Any updates on this, I would like to see this on hackage as well, as this package isn't the easiest to find.

**Comment by ocharles** [comment]
Closing issues here now that [`tar-conduit`](http://hackage.haskell.org/package/tar-conduit) is out. I no longer need this project, so it's unlikely to see the light of day any time soon.

**Comment by FranklinChen** [comment]
Got it. Thanks.
